language: node_js
node_js:
  - 6
cache:
  directories:
    - client/node_modules
    - server/node_modules
before_install:
  - npm install -g @angular/cli@1.1.1
install:
  - cd client
  - npm install
  - npm install enhanced-resolve@3.3.0 #workaroun for angular cli issue: Can't resolve './$$_gendir/app/app.module.ngfactory'
  - ng build -prod
  - cd ../server
  - npm install
script:
  - cp -rf ../client/dist ./client
  - zip rcr-national-archive.zip