language: node_js
node_js:
  - 6
cache:
  directories:
    - client/node_modules
    - server/node_modules
before_install:
  - npm install -g @angular/cli@1.1.1
install:
  - cd client
  - npm install
  - npm install enhanced-resolve@3.3.0 #workaround for angular cli issue: Can't resolve './$$_gendir/app/app.module.ngfactory'
  - ng build -prod
  - cd dist
  - mv index.html 200.html
script: true
deploy:
  provider: surge
  project: ./client/dist/
  domain: rcr-national-archive.surge.sh
  skip_cleanup: true